from pylab import plot, show, xlim,ylim, xlabel
from numpy import linspace,sin, loadtxt,cos
x=linspace(0,10,100)
print(x)
y=sin(x)
#plot(x,y)
show()
a=open("test.dat","w")
for i in range(len(x)):
    a.write("%.2f %.2f\n" %(x[i],y[i]))
a.close()
b=loadtxt("test.dat",float)
print(b[:,0])
print(b[:,1])
plot(b[:,0],b[:,1])
ylim(-1.1,1.1)
plot(x,y,"ko")
plot(x,y,"g--")
w=sin(x)
m=cos(x)
plot(x,m)
xlabel("radians")
show()
